development:
  clients:
    default:
      database: hunger_users_development
      hosts:
        - hunger_users_service_db:27017
      options:
        server_selection_timeout: 1

test:
  clients:
    default:
      database: hunger_users_test
      hosts:
        - hunger_users_service_db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
