# frozen_string_literal: true

Category.create(
  [
    { name: 'Afghan', identifier: 'afghani', main: false },
    { name: 'African', identifier: 'african', main: false },
    { name: 'Andalusian', identifier: 'andalusian', main: false },
    { name: 'Arabian', identifier: 'arabian', main: false },
    { name: 'Argentine', identifier: 'argentine', main: false },
    { name: 'Armenian', identifier: 'armenian', main: false },
    { name: 'Asian Fusion', identifier: 'asianfusion', main: false },
    { name: 'Asturian', identifier: 'asturian', main: false },
    { name: 'Australian', identifier: 'australian', main: false },
    { name: 'Austrian', identifier: 'austrian', main: false },
    { name: 'Baguettes', identifier: 'baguettes', main: false },
    { name: 'Bangladeshi', identifier: 'bangladeshi', main: false },
    { name: 'Basque', identifier: 'basque', main: false },
    { name: 'Bavarian', identifier: 'bavarian', main: false },
    { name: 'Barbeque', identifier: 'bbq', main: false },
    { name: 'Beer Garden', identifier: 'beergarden', main: false },
    { name: 'Beer Hall', identifier: 'beerhall', main: false },
    { name: 'Beisl', identifier: 'beisl', main: false },
    { name: 'Belgian', identifier: 'belgian', main: false },
    { name: 'Bistros', identifier: 'bistros', main: false },
    { name: 'Black Sea', identifier: 'blacksea', main: false },
    { name: 'Brasseries', identifier: 'brasseries', main: false },
    { name: 'Brazilian', identifier: 'brazilian', main: false },
    { name: 'Breakfast & Brunch', identifier: 'breakfast_brunch', main: false },
    { name: 'British', identifier: 'british', main: false },
    { name: 'Buffets', identifier: 'buffets', main: false },
    { name: 'Bulgarian', identifier: 'bulgarian', main: false },
    { name: 'Burgers', identifier: 'burgers', main: false },
    { name: 'Burmese', identifier: 'burmese', main: false },
    { name: 'Cafes', identifier: 'cafes', main: false },
    { name: 'Cafeteria', identifier: 'cafeteria', main: false },
    { name: 'Cajun/Creole', identifier: 'cajun', main: false },
    { name: 'Cambodian', identifier: 'cambodian', main: false },
    { name: 'Canteen', identifier: 'canteen', main: false },
    { name: 'Caribbean', identifier: 'caribbean', main: false },
    { name: 'Catalan', identifier: 'catalan', main: false },
    { name: 'Cheesesteaks', identifier: 'cheesesteaks', main: false },
    { name: 'Chicken Wings', identifier: 'chicken_wings', main: false },
    { name: 'Chicken Shop', identifier: 'chickenshop', main: false },
    { name: 'Chilean', identifier: 'chilean', main: false },
    { name: 'Chinese', identifier: 'chinese', main: true },
    { name: 'Comfort Food', identifier: 'comfortfood', main: false },
    { name: 'Corsican', identifier: 'corsican', main: false },
    { name: 'Creperies', identifier: 'creperies', main: false },
    { name: 'Cuban', identifier: 'cuban', main: false },
    { name: 'Curry Sausage', identifier: 'currysausage', main: false },
    { name: 'Cypriot', identifier: 'cypriot', main: false },
    { name: 'Czech', identifier: 'czech', main: false },
    { name: 'Czech/Slovakian', identifier: 'czechslovakian', main: false },
    { name: 'Danish', identifier: 'danish', main: false },
    { name: 'Delis', identifier: 'delis', main: false },
    { name: 'Diners', identifier: 'diners', main: false },
    { name: 'Dinner Theater', identifier: 'dinnertheater', main: false },
    { name: 'Dumplings', identifier: 'dumplings', main: false },
    { name: 'Eastern European', identifier: 'eastern_european', main: false },
    { name: 'Parent Cafes', identifier: 'eltern_cafes', main: false },
    { name: 'Eritrean', identifier: 'eritrean', main: false },
    { name: 'Ethiopian', identifier: 'ethiopian', main: false },
    { name: 'Filipino', identifier: 'filipino', main: false },
    { name: 'Fischbroetchen', identifier: 'fischbroetchen', main: false },
    { name: 'Fish & Chips', identifier: 'fishnchips', main: false },
    { name: 'Flatbread', identifier: 'flatbread', main: false },
    { name: 'Fondue', identifier: 'fondue', main: false },
    { name: 'Food Court', identifier: 'food_court', main: false },
    { name: 'Food Stands', identifier: 'foodstands', main: false },
    { name: 'Freiduria', identifier: 'freiduria', main: false },
    { name: 'French', identifier: 'french', main: false },
    { name: 'Galician', identifier: 'galician', main: false },
    { name: 'Game Meat', identifier: 'gamemeat', main: false },
    { name: 'Gastropubs', identifier: 'gastropubs', main: false },
    { name: 'Georgian', identifier: 'georgian', main: false },
    { name: 'German', identifier: 'german', main: false },
    { name: 'Giblets', identifier: 'giblets', main: false },
    { name: 'Gluten-Free', identifier: 'gluten_free', main: false },
    { name: 'Greek', identifier: 'greek', main: false },
    { name: 'Guamanian', identifier: 'guamanian', main: false },
    { name: 'Halal', identifier: 'halal', main: false },
    { name: 'Hawaiian', identifier: 'hawaiian', main: false },
    { name: 'Heuriger', identifier: 'heuriger', main: false },
    { name: 'Himalayan/Nepalese', identifier: 'himalayan', main: false },
    { name: 'Hong Kong Style Cafe', identifier: 'hkcafe', main: false },
    { name: 'Honduran', identifier: 'honduran', main: false },
    { name: 'Hot Dogs', identifier: 'hotdog', main: false },
    { name: 'Fast Food', identifier: 'hotdogs', main: false },
    { name: 'Hot Pot', identifier: 'hotpot', main: false },
    { name: 'Hungarian', identifier: 'hungarian', main: false },
    { name: 'Iberian', identifier: 'iberian', main: false },
    { name: 'Indonesian', identifier: 'indonesian', main: false },
    { name: 'Indian', identifier: 'indpak', main: false },
    { name: 'International', identifier: 'international', main: false },
    { name: 'Irish', identifier: 'irish', main: false },
    { name: 'Island Pub', identifier: 'island_pub', main: false },
    { name: 'Israeli', identifier: 'israeli', main: false },
    { name: 'Italian', identifier: 'italian', main: true },
    { name: 'Japanese', identifier: 'japanese', main: true },
    { name: 'Jewish', identifier: 'jewish', main: false },
    { name: 'Kebab', identifier: 'kebab', main: false },
    { name: 'Kopitiam', identifier: 'kopitiam', main: false },
    { name: 'Korean', identifier: 'korean', main: false },
    { name: 'Kosher', identifier: 'kosher', main: false },
    { name: 'Kurdish', identifier: 'kurdish', main: false },
    { name: 'Laos', identifier: 'laos', main: false },
    { name: 'Laotian', identifier: 'laotian', main: false },
    { name: 'Latin American', identifier: 'latin', main: false },
    { name: 'Lyonnais', identifier: 'lyonnais', main: false },
    { name: 'Malaysian', identifier: 'malaysian', main: false },
    { name: 'Meatballs', identifier: 'meatballs', main: false },
    { name: 'Mediterranean', identifier: 'mediterranean', main: false },
    { name: 'Mexican', identifier: 'mexican', main: true },
    { name: 'Middle Eastern', identifier: 'mideastern', main: false },
    { name: 'Milk Bars', identifier: 'milkbars', main: false },
    { name: 'Modern Australian', identifier: 'modern_australian', main: false },
    { name: 'Modern European', identifier: 'modern_european', main: false },
    { name: 'Mongolian', identifier: 'mongolian', main: false },
    { name: 'Moroccan', identifier: 'moroccan', main: false },
    { name: 'American (New)', identifier: 'newamerican', main: false },
    { name: 'Canadian (New)', identifier: 'newcanadian', main: false },
    { name: 'New Mexican Cuisine', identifier: 'newmexican', main: false },
    { name: 'New Zealand', identifier: 'newzealand', main: false },
    { name: 'Nicaraguan', identifier: 'nicaraguan', main: false },
    { name: 'Night Food', identifier: 'nightfood', main: false },
    { name: 'Nikkei', identifier: 'nikkei', main: false },
    { name: 'Noodles', identifier: 'noodles', main: false },
    { name: 'Norcinerie', identifier: 'norcinerie', main: false },
    { name: 'Traditional Norwegian', identifier: 'norwegian', main: false },
    { name: 'Open Sandwiches', identifier: 'opensandwiches', main: false },
    { name: 'Oriental', identifier: 'oriental', main: false },
    { name: 'Pakistani', identifier: 'pakistani', main: false },
    { name: 'Pan Asian', identifier: 'panasian', main: false },
    { name: 'Parma', identifier: 'parma', main: false },
    { name: 'Persian/Iranian', identifier: 'persian', main: false },
    { name: 'Peruvian', identifier: 'peruvian', main: false },
    { name: 'PF/Comercial', identifier: 'pfcomercial', main: false },
    { name: 'Pita', identifier: 'pita', main: false },
    { name: 'Pizza', identifier: 'pizza', main: false },
    { name: 'Polish', identifier: 'polish', main: false },
    { name: 'Polynesian', identifier: 'polynesian', main: false },
    { name: 'Pop-Up Restaurants', identifier: 'popuprestaurants', main: false },
    { name: 'Portuguese', identifier: 'portuguese', main: false },
    { name: 'Potatoes', identifier: 'potatoes', main: false },
    { name: 'Poutineries', identifier: 'poutineries', main: false },
    { name: 'Pub Food', identifier: 'pubfood', main: false },
    { name: 'Live/Raw Food', identifier: 'raw_food', main: false },
    { name: 'Rice', identifier: 'riceshop', main: false },
    { name: 'Romanian', identifier: 'romanian', main: false },
    { name: 'Rotisserie Chicken', identifier: 'rotisserie_chicken', main: false },
    { name: 'Russian', identifier: 'russian', main: false },
    { name: 'Salad', identifier: 'salad', main: false },
    { name: 'Sandwiches', identifier: 'sandwiches', main: false },
    { name: 'Scandinavian', identifier: 'scandinavian', main: false },
    { name: 'Schnitzel', identifier: 'schnitzel', main: false },
    { name: 'Scottish', identifier: 'scottish', main: false },
    { name: 'Seafood', identifier: 'seafood', main: false },
    { name: 'Serbo Croatian', identifier: 'serbocroatian', main: false },
    { name: 'Signature Cuisine', identifier: 'signature_cuisine', main: false },
    { name: 'Singaporean', identifier: 'singaporean', main: false },
    { name: 'Slovakian', identifier: 'slovakian', main: false },
    { name: 'Somali', identifier: 'somali', main: false },
    { name: 'Soul Food', identifier: 'soulfood', main: false },
    { name: 'Soup', identifier: 'soup', main: false },
    { name: 'Southern', identifier: 'southern', main: false },
    { name: 'Spanish', identifier: 'spanish', main: false },
    { name: 'Sri Lankan', identifier: 'srilankan', main: false },
    { name: 'Steakhouses', identifier: 'steak', main: false },
    { name: 'French Southwest', identifier: 'sud_ouest', main: false },
    { name: 'Supper Clubs', identifier: 'supperclubs', main: false },
    { name: 'Sushi Bars', identifier: 'sushi', main: false },
    { name: 'Swabian', identifier: 'swabian', main: false },
    { name: 'Swedish', identifier: 'swedish', main: false },
    { name: 'Swiss Food', identifier: 'swissfood', main: false },
    { name: 'Syrian', identifier: 'syrian', main: false },
    { name: 'Tabernas', identifier: 'tabernas', main: false },
    { name: 'Taiwanese', identifier: 'taiwanese', main: false },
    { name: 'Tapas Bars', identifier: 'tapas', main: true },
    { name: 'Tapas/Small Plates', identifier: 'tapasmallplates', main: false },
    { name: 'Tavola Calda', identifier: 'tavolacalda', main: false },
    { name: 'Tex-Mex', identifier: 'tex-mex', main: false },
    { name: 'Thai', identifier: 'thai', main: false },
    { name: 'American (Traditional)', identifier: 'tradamerican', main: true },
    { name: 'Traditional Swedish', identifier: 'traditional_swedish', main: false },
    { name: 'Trattorie', identifier: 'trattorie', main: false },
    { name: 'Turkish', identifier: 'turkish', main: false },
    { name: 'Ukrainian', identifier: 'ukrainian', main: false },
    { name: 'Uzbek', identifier: 'uzbek', main: false },
    { name: 'Vegan', identifier: 'vegan', main: false },
    { name: 'Vegetarian', identifier: 'vegetarian', main: false },
    { name: 'Venison', identifier: 'venison', main: false },
    { name: 'Vietnamese', identifier: 'vietnamese', main: false },
    { name: 'Waffles', identifier: 'waffles', main: false },
    { name: 'Wok', identifier: 'wok', main: false },
    { name: 'Wraps', identifier: 'wraps', main: false },
    { name: 'Yugoslav', identifier: 'yugoslav' }
  ]
)
