# frozen_string_literal: true

Category.create(
  [
    { name: 'Afghan', identifier: 'afghani'},
    { name: 'African', identifier: 'african' },
    { name: 'Andalusian', identifier: 'andalusian' },
    { name: 'Arabian', identifier: 'arabian' },
    { name: 'Argentine', identifier: 'argentine' },
    { name: 'Armenian', identifier: 'armenian' },
    { name: 'Asian Fusion', identifier: 'asianfusion' },
    { name: 'Asturian', identifier: 'asturian' },
    { name: 'Australian', identifier: 'australian' },
    { name: 'Austrian', identifier: 'austrian' },
    { name: 'Baguettes', identifier: 'baguettes' },
    { name: 'Bangladeshi', identifier: 'bangladeshi' },
    { name: 'Basque', identifier: 'basque' },
    { name: 'Bavarian', identifier: 'bavarian' },
    { name: 'Barbeque', identifier: 'bbq' },
    { name: 'Beer Garden', identifier: 'beergarden' },
    { name: 'Beer Hall', identifier: 'beerhall' },
    { name: 'Beisl', identifier: 'beisl' },
    { name: 'Belgian', identifier: 'belgian' },
    { name: 'Bistros', identifier: 'bistros' },
    { name: 'Black Sea', identifier: 'blacksea' },
    { name: 'Brasseries', identifier: 'brasseries' },
    { name: 'Brazilian', identifier: 'brazilian' },
    { name: 'Breakfast & Brunch', identifier: 'breakfast_brunch' },
    { name: 'British', identifier: 'british' },
    { name: 'Buffets', identifier: 'buffets' },
    { name: 'Bulgarian', identifier: 'bulgarian' },
    { name: 'Burgers', identifier: 'burgers' },
    { name: 'Burmese', identifier: 'burmese' },
    { name: 'Cafes', identifier: 'cafes' },
    { name: 'Cafeteria', identifier: 'cafeteria' },
    { name: 'Cajun/Creole', identifier: 'cajun' },
    { name: 'Cambodian', identifier: 'cambodian' },
    { name: 'Canteen', identifier: 'canteen' },
    { name: 'Caribbean', identifier: 'caribbean' },
    { name: 'Catalan', identifier: 'catalan' },
    { name: 'Cheesesteaks', identifier: 'cheesesteaks' },
    { name: 'Chicken Wings', identifier: 'chicken_wings' },
    { name: 'Chicken Shop', identifier: 'chickenshop' },
    { name: 'Chilean', identifier: 'chilean' },
    { name: 'Chinese', identifier: 'chinese' },
    { name: 'Comfort Food', identifier: 'comfortfood' },
    { name: 'Corsican', identifier: 'corsican' },
    { name: 'Creperies', identifier: 'creperies' },
    { name: 'Cuban', identifier: 'cuban' },
    { name: 'Curry Sausage', identifier: 'currysausage' },
    { name: 'Cypriot', identifier: 'cypriot' },
    { name: 'Czech', identifier: 'czech' },
    { name: 'Czech/Slovakian', identifier: 'czechslovakian' },
    { name: 'Danish', identifier: 'danish' },
    { name: 'Delis', identifier: 'delis' },
    { name: 'Diners', identifier: 'diners' },
    { name: 'Dinner Theater', identifier: 'dinnertheater' },
    { name: 'Dumplings', identifier: 'dumplings' },
    { name: 'Eastern European', identifier: 'eastern_european' },
    { name: 'Parent Cafes', identifier: 'eltern_cafes' },
    { name: 'Eritrean', identifier: 'eritrean' },
    { name: 'Ethiopian', identifier: 'ethiopian' },
    { name: 'Filipino', identifier: 'filipino' },
    { name: 'Fischbroetchen', identifier: 'fischbroetchen' },
    { name: 'Fish & Chips', identifier: 'fishnchips' },
    { name: 'Flatbread', identifier: 'flatbread' },
    { name: 'Fondue', identifier: 'fondue' },
    { name: 'Food Court', identifier: 'food_court' },
    { name: 'Food Stands', identifier: 'foodstands' },
    { name: 'Freiduria', identifier: 'freiduria' },
    { name: 'French', identifier: 'french' },
    { name: 'Galician', identifier: 'galician' },
    { name: 'Game Meat', identifier: 'gamemeat' },
    { name: 'Gastropubs', identifier: 'gastropubs' },
    { name: 'Georgian', identifier: 'georgian' },
    { name: 'German', identifier: 'german' },
    { name: 'Giblets', identifier: 'giblets' },
    { name: 'Gluten-Free', identifier: 'gluten_free' },
    { name: 'Greek', identifier: 'greek' },
    { name: 'Guamanian', identifier: 'guamanian' },
    { name: 'Halal', identifier: 'halal' },
    { name: 'Hawaiian', identifier: 'hawaiian' },
    { name: 'Heuriger', identifier: 'heuriger' },
    { name: 'Himalayan/Nepalese', identifier: 'himalayan' },
    { name: 'Hong Kong Style Cafe', identifier: 'hkcafe' },
    { name: 'Honduran', identifier: 'honduran' },
    { name: 'Hot Dogs', identifier: 'hotdog' },
    { name: 'Fast Food', identifier: 'hotdogs' },
    { name: 'Hot Pot', identifier: 'hotpot' },
    { name: 'Hungarian', identifier: 'hungarian' },
    { name: 'Iberian', identifier: 'iberian' },
    { name: 'Indonesian', identifier: 'indonesian' },
    { name: 'Indian', identifier: 'indpak' },
    { name: 'International', identifier: 'international' },
    { name: 'Irish', identifier: 'irish' },
    { name: 'Island Pub', identifier: 'island_pub' },
    { name: 'Israeli', identifier: 'israeli' },
    { name: 'Italian', identifier: 'italian' },
    { name: 'Japanese', identifier: 'japanese' },
    { name: 'Jewish', identifier: 'jewish' },
    { name: 'Kebab', identifier: 'kebab' },
    { name: 'Kopitiam', identifier: 'kopitiam' },
    { name: 'Korean', identifier: 'korean' },
    { name: 'Kosher', identifier: 'kosher' },
    { name: 'Kurdish', identifier: 'kurdish' },
    { name: 'Laos', identifier: 'laos' },
    { name: 'Laotian', identifier: 'laotian' },
    { name: 'Latin American', identifier: 'latin' },
    { name: 'Lyonnais', identifier: 'lyonnais' },
    { name: 'Malaysian', identifier: 'malaysian' },
    { name: 'Meatballs', identifier: 'meatballs' },
    { name: 'Mediterranean', identifier: 'mediterranean' },
    { name: 'Mexican', identifier: 'mexican' },
    { name: 'Middle Eastern', identifier: 'mideastern' },
    { name: 'Milk Bars', identifier: 'milkbars' },
    { name: 'Modern Australian', identifier: 'modern_australian' },
    { name: 'Modern European', identifier: 'modern_european' },
    { name: 'Mongolian', identifier: 'mongolian' },
    { name: 'Moroccan', identifier: 'moroccan' },
    { name: 'American (New)', identifier: 'newamerican' },
    { name: 'Canadian (New)', identifier: 'newcanadian' },
    { name: 'New Mexican Cuisine', identifier: 'newmexican' },
    { name: 'New Zealand', identifier: 'newzealand' },
    { name: 'Nicaraguan', identifier: 'nicaraguan' },
    { name: 'Night Food', identifier: 'nightfood' },
    { name: 'Nikkei', identifier: 'nikkei' },
    { name: 'Noodles', identifier: 'noodles' },
    { name: 'Norcinerie', identifier: 'norcinerie' },
    { name: 'Traditional Norwegian', identifier: 'norwegian' },
    { name: 'Open Sandwiches', identifier: 'opensandwiches' },
    { name: 'Oriental', identifier: 'oriental' },
    { name: 'Pakistani', identifier: 'pakistani' },
    { name: 'Pan Asian', identifier: 'panasian' },
    { name: 'Parma', identifier: 'parma' },
    { name: 'Persian/Iranian', identifier: 'persian' },
    { name: 'Peruvian', identifier: 'peruvian' },
    { name: 'PF/Comercial', identifier: 'pfcomercial' },
    { name: 'Pita', identifier: 'pita' },
    { name: 'Pizza', identifier: 'pizza' },
    { name: 'Polish', identifier: 'polish' },
    { name: 'Polynesian', identifier: 'polynesian' },
    { name: 'Pop-Up Restaurants', identifier: 'popuprestaurants' },
    { name: 'Portuguese', identifier: 'portuguese' },
    { name: 'Potatoes', identifier: 'potatoes' },
    { name: 'Poutineries', identifier: 'poutineries' },
    { name: 'Pub Food', identifier: 'pubfood' },
    { name: 'Live/Raw Food', identifier: 'raw_food' },
    { name: 'Rice', identifier: 'riceshop' },
    { name: 'Romanian', identifier: 'romanian' },
    { name: 'Rotisserie Chicken', identifier: 'rotisserie_chicken' },
    { name: 'Russian', identifier: 'russian' },
    { name: 'Salad', identifier: 'salad' },
    { name: 'Sandwiches', identifier: 'sandwiches' },
    { name: 'Scandinavian', identifier: 'scandinavian' },
    { name: 'Schnitzel', identifier: 'schnitzel' },
    { name: 'Scottish', identifier: 'scottish' },
    { name: 'Seafood', identifier: 'seafood' },
    { name: 'Serbo Croatian', identifier: 'serbocroatian' },
    { name: 'Signature Cuisine', identifier: 'signature_cuisine' },
    { name: 'Singaporean', identifier: 'singaporean' },
    { name: 'Slovakian', identifier: 'slovakian' },
    { name: 'Somali', identifier: 'somali' },
    { name: 'Soul Food', identifier: 'soulfood' },
    { name: 'Soup', identifier: 'soup' },
    { name: 'Southern', identifier: 'southern' },
    { name: 'Spanish', identifier: 'spanish' },
    { name: 'Sri Lankan', identifier: 'srilankan' },
    { name: 'Steakhouses', identifier: 'steak' },
    { name: 'French Southwest', identifier: 'sud_ouest' },
    { name: 'Supper Clubs', identifier: 'supperclubs' },
    { name: 'Sushi Bars', identifier: 'sushi' },
    { name: 'Swabian', identifier: 'swabian' },
    { name: 'Swedish', identifier: 'swedish' },
    { name: 'Swiss Food', identifier: 'swissfood' },
    { name: 'Syrian', identifier: 'syrian' },
    { name: 'Tabernas', identifier: 'tabernas' },
    { name: 'Taiwanese', identifier: 'taiwanese' },
    { name: 'Tapas Bars', identifier: 'tapas' },
    { name: 'Tapas/Small Plates', identifier: 'tapasmallplates' },
    { name: 'Tavola Calda', identifier: 'tavolacalda' },
    { name: 'Tex-Mex', identifier: 'tex-mex' },
    { name: 'Thai', identifier: 'thai' },
    { name: 'American (Traditional)', identifier: 'tradamerican' },
    { name: 'Traditional Swedish', identifier: 'traditional_swedish' },
    { name: 'Trattorie', identifier: 'trattorie' },
    { name: 'Turkish', identifier: 'turkish' },
    { name: 'Ukrainian', identifier: 'ukrainian' },
    { name: 'Uzbek', identifier: 'uzbek' },
    { name: 'Vegan', identifier: 'vegan' },
    { name: 'Vegetarian', identifier: 'vegetarian' },
    { name: 'Venison', identifier: 'venison' },
    { name: 'Vietnamese', identifier: 'vietnamese' },
    { name: 'Waffles', identifier: 'waffles' },
    { name: 'Wok', identifier: 'wok' },
    { name: 'Wraps', identifier: 'wraps' },
    { name: 'Yugoslav', identifier: 'yugoslav' }
  ]
)
